### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by jtroe** [goodeggs/st-multi-sort#1]
Would like to get this package on the bower repository

**Comment by ljantzen** [comment]
I have made a fork (+ pull request).  This component is now bower installable by using the name st-multi-sort-lja ).  

An additional feature in my fork is the possibility  to ctrl-click on a column header. It has the same functionality as alt-clicking with regards to sorting, but (at least on linux) doesnt awkwardly select the text in the column headers, inverting the colors in the process.

**Comment by dannynelson** [comment]
This is merged now. Thanks @ljantzen
