### ISSUE TITLE
sort column elementId not persisting

### ISSUE THREAD

**Issue by newbro** [goodeggs/st-multi-sort#5]
I am using ng-repeat to generate my st-table thead like so:
```
<thead icon-up="glyphicon glyphicon-sort-by-alphabet" icon-down="glyphicon glyphicon-sort-by-alphabet-alt">
              <th ng-repeat="field in tableHeaders" st-multi-sort="{{field.key}}">
                {{ field.name }}
              </th>
```
This seems to have problem with st-multi-sort because whenever i tried sorting a column, the sort state will not persist upon table reload (I'm using st-pipe to reload data from server). I have tried dumping the tableState and it seems the sort column elementId keep on incrementing and not persisted, so the tableState.sort.predicate array will keep on expanding if I repeat clicking on the very same column header. 

If you have any insight on whether I can resolve this that would be great.

**Comment by newbro** [comment]
Spoke too soon, it seems disabling 2-way binding solved it:

`<th ng-repeat="field in ::tableHeaders" st-multi-sort="{{field.key}}">`

Please help to close this. Thanks.

**Comment by dannynelson** [comment]
:+1:
